name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

#    - name: Enter python project
#      run: cd app_python

    - name: Install dependencies
      run: |
        cd app_python
        pip install -r requirements.txt

    - name: Lint code
      run: flake8

    - name: Run tests
      run: python -m unittest tests.py

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t app_python:latest .
        docker tag app_python:latest ${{ secrets.DOCKER_USERNAME }}/app_python:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/app_python:latest
      env:
        DOCKER_CLI_ACI: 1
